- alias: 'lights_off_bedtime_week'

  trigger:
    platform: time
    after: "22:15"

  condition:
    condition: and
    conditions:

    - condition: state
      entity_id: media_player.plex_shield_tv
      state: 'idle'
    - condition: state
      entity_id: input_boolean.disable_bedtime
      state: 'off'
    - condition: state
      entity_id: input_boolean.enable_guest
      state: 'off'
    - condition: state
      entity_id: input_boolean.bedtime_normal
      state: 'on'
    - condition: time
      weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
       - sat
       - sun

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_living_room
    data:
      transition: 2
