- alias: auto_bot_ping
  id: auto_bot_ping
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
      # Type "/ping" in the no.33 bot

  action:
  - service: notify.bot
    data:
      message: 'pong'
      # Reply "pong" to no.33 bot

########################

- alias: auto_bot_restart
  id: auto_bot_restart
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/restart'
      # Type "/restart" in the no.33 bot

  action:
  - service: notify.bot
    data:
      message: 'restarting hass'
      # Reply "restarting hass" in no.33 bot
#- service: homeassistant.restart
  - service: script.restart_hass
    # Restarts homeassistant docker

########################

- alias: auto_bot_reload
  id: auto_bot_reload
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/reload'
      # Type "/reload" in the no.33 bot

  action:
  - service: notify.bot
    data:
      message: 'reloading core config'
      # Reply "reloading core config" inside the no.33 bot
  - service: homeassistant.reload_core_config
    # Reloads homeassistant

########################

- alias: auto_bot_check_config
  id: auto_bot_check_config
  initial_state: True

  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/config'
      # Type "/config" in the no.33 bot

  action:
  - service: notify.bot
    data:
      message: 'checking config'
      # Reply "checking config" inside the no.33 bot
  - service: homeassistant.check_config
    # Checks homeassistant config
