- alias: lights_on_sunset_outside
  initial_state: True

  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00:00'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/outside'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Outside"
      scene_name: "Full"

########################

- alias: lights_dim_night_outside
  initial_state: True

  trigger:
  # - platform: time
  #   after: '22:30:00'
  - platform: time
    at: '22:30:00'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Outside"
      scene_name: "Dim"

########################

- alias: lights_off_morning_outside
  initial_state: True

  trigger:
  - platform: sun
    event: sunrise
    offset: '1:00:00'

  # - platform: time
  #   after: '08:30:00'
  - platform: time
    at: '08:30:00'
  # - platform: time
  #   after: '08:35:00'
  - platform: time
    at: '08:35:00'
  # - platform: time
  #   after: '08:40:00'
  - platform: time
    at: '08:40:00'

  action:
  - service: scene.turn_on
    entity_id: scene.hue_outside_off
