- alias: lights_off_morning_inside

  trigger:
  - platform: time
    after: '08:45:00'
  - platform: time
    after: '08:50:00'

  condition:
    condition: and
    conditions:

    - condition: state
      entity_id: input_boolean.disable_work
      state: 'off'
    - condition: state
      entity_id: input_boolean.enable_guest
      state: 'off'
    - condition: time
      weekday:
       - mon
       - tue
       - wed
       - thu
       - fri

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_living_room
    data:
      transition: 2

- alias: lights_off_bedtime_inside

  trigger:
    platform: time
    after: '22:15:00'

  condition:
    condition: and
    conditions:

    - condition: state
      entity_id: media_player.plex_shield
      state: 'idle'
    - condition: state
      entity_id: input_boolean.disable_bedtime
      state: 'off'
    - condition: state
      entity_id: input_boolean.enable_guest
      state: 'off'

  action:
    service: homeassistant.turn_off
    entity_id: light.hue_living_room
    data:
      transition: 2
