- alias: lights_on_sunset_inside

  trigger:
  - platform: time
    after: '17:30:00'
  - platform: sun
    event: sunset
    offset: '-1:30:00'

  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.disable_sunset
      state: 'off'
    - condition: state
      entity_id: group.living_room_lights
      state: 'off'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Full"
