- alias: 'lights_on_morning_inside'

  trigger:
    platform: time
    after: '05:55:00'

  condition:
    condition: state
    entity_id: group.living_room_lights
    state: 'off'

  action:
    service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Dim"
