- alias: plex_now_stopped_tvshow
  initial_state: True

  trigger:
  - platform: state
    entity_id:
    - media_player.plex_shield
    from: 'playing'
    # Triggers if plex is paused or stopped

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.plex_tvshow
        state: 'on'
        # Only triggers if watching a tv show
      - condition: or
        conditions:
        - condition: time
          after: "17:30:00"
          # Only trigger after 5.30 pm
        - condition: sun
          after: sunset
          after_offset: "-1:30:00"
          # Or if the sun has set
        - condition: state
          entity_id: input_boolean.simulate_sunset
          state: 'on'
          # Or if simulate sunset is on

      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.enable_guest
          state: 'off'
          # Don't trigger if we have guests
        - condition: state
          entity_id: input_boolean.disable_plex
          state: 'off'
          # Don't trigger if disable plex is on

  action:
  - service: homeassistant.turn_on
    entity_id: scene.now_stopped_tvshow
    # Activates now stopped scene
  - service: light.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Full"
      # Activates native Hue scene 'Full'
