- name: input_guests
  entities:
    input_boolean.disable_bedtime: on
    input_boolean.disable_plex: on
    input_boolean.disable_work: on
    input_boolean.simulate_sunset: off

- name: input_after_sunset
  entities:
      input_boolean.simulate_sunset: on

- name: input_reset
  entities:
    input_boolean.disable_bedtime: off
    input_boolean.disable_plex: off
    input_boolean.disable_sunset: off
    input_boolean.simulate_sunset: off
    input_boolean.disable_work: off

- name: input_tts
  entities:
    input_boolean.text_to_speech: off

- name: james_is_home
  entities:
    input_boolean.james_is_at_home: on

- name: james_is_away
  entities:
    input_boolean.james_is_at_home: off

- name: gillian_is_home
  entities:
    input_boolean.gillian_is_at_home: on

- name: gillian_is_away
  entities:
    input_boolean.gillian_is_at_home: off

- name: bedtime_on
  entities:
    input_boolean.bedtime: on

- name: bedtime_off
  entities:
    input_boolean.bedtime: off
