### Reset scene restores all input boolean switches to off

- name: 'input_reset'
  entities:
    input_boolean.disable_bedtime:
        state: off
    input_boolean.disable_plex:
        state: off
    input_boolean.disable_sunset:
        state: off
    input_boolean.simulate_sunset:
        state: off
