telegram_bot:
  platform: polling
  api_key: !secret telegram_api
  allowed_chat_ids:
    - !secret telegram_id
  # Telegram polling bot allows control of hass
  # from outside lan without any open ports

#tts:
#  - platform: google
