script:
  hue_dim:
    alias: Dim
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_full:
    alias: Full
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Full"

  hue_morning:
    alias: Morning
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_movie:
    alias: Movie
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Movie"

  hue_night:
    alias: Night
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Night"

  hue_white:
    alias: White
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "White"

  hue_outside_full:
    alias: Outside Full
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Outside"
          scene_name: "Full"

group:

  all_scripts:
      name: All Scripts
      entities:
      - group.scripts

  scripts:
      name: Hue Scripts
      entities:
      - script.hue_dim
      - script.hue_full
      - script.hue_movie
      - script.hue_morning
      - script.hue_white
      - script.hue_night
      - script.hue_outside_full

  scenes:
      name: Hue Scenes
      entities:
      - scene.hue_dim
      - scene.hue_full
      - scene.hue_movie
      - scene.hue_morning
      - scene.hue_white
      - scene.hue_night
