group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus3
      - device_tracker.james_tado
      # - sensor.james_oneplus3
      # - sensor.james_tado

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus3
      - device_tracker.gillian_tado
      # - sensor.gillian_oneplus3
      # - sensor.gillian_tado

  home:
      name: Home
      entities:
      # - group.james
      # - group.gillian
      - sensor.james_group
      - sensor.gillian_group
      - input_boolean.enable_guest
