group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus_3
      - device_tracker.james_tado
      - device_tracker.james_ping

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus_3
      - device_tracker.gillian_tado
      - device_tracker.gillian_ping

  home:
      name: Home
      control: hidden
      entities:
      # - group.james
      # - group.gillian
      - sensor.james_group
      - sensor.gillian_group
      - sensor.heating_temperature
      - sensor.heating_humidity
      - sensor.motion_hue_living_room
      - input_boolean.enable_guest
      - input_boolean.text_to_speech
