group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus3
      - device_tracker.james_tado
      - device_tracker.james_ping

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus3
      - device_tracker.gillian_tado
      - device_tracker.gillian_ping

  home:
      name: Home
      entities:
      - group.james
      - group.gillian

homeassistant:
  customize:
    group.james:
      entity_picture: /local/hansolo.png
    group.gillian:
      entity_picture: /local/leia.png

  customize_glob:
    "device_tracker.james*":
      entity_picture: /local/anakin.png
    "device_tracker.gillian*":
      entity_picture: /local/hologram.png
