group:
  james:
      name: James
      entities:
      - device_tracker.james_oneplus3
      - device_tracker.james_tado
      - device_tracker.james_ping

  gillian:
      name: Gillian
      entities:
      - device_tracker.gillian_oneplus3t
      - device_tracker.gillian_tado
      - device_tracker.gillian_ping

  home:
      name: Home
      control: hidden
      entities:
      - binary_sensor.james_home
      - binary_sensor.gillian_home
      - sensor.james_home
      - sensor.gillian_home
      - sensor.heating_temperature
      - sensor.heating_humidity
      - sensor.motion_hue_living_room
      - sensor.hue_tap
      - input_boolean.enable_guest
      - input_boolean.text_to_speech
