###############################
########### PLEX ##############
###############################

media_player:
  - platform: plex
    entity_namespace: 'plex'
    # include_non_clients: true
    scan_interval: 2

###############################
########### CAST ##############
###############################

  - platform: cast
    entity_namespace: 'cast'
    host: !secret cast_ip

###############################
########### KODI ##############
###############################

  - platform: kodi
    entity_namespace: 'kodi'
    host: !secret cast_ip
    port: 8033
    
###############################
########### SONYTV #############
###############################

  - platform: braviatv_psk
    name: Bravia4k
    host: !secret sony_ip
    psk: !secret sony_psk
    mac: !secret sony_mac
    amp: True
    android: True
    sourcefilter:
      - HDMI
    
###############################
### ALL-IN-ONE MEDIA CENTRE ###
###############################

  - platform: universal
    name: MEDIA CENTRE
    children:
       - media_player.sonos_all_universal
       - media_player.plex_shield
       - media_player.kodi_kodi
       - media_player.cast_shield

###############################
######### PLEX SENSOR #########
###############################

sensor:
  - platform: plex
    name: plex_shield
    host: !secret plex_ip

###############################
### ALL-IN-ONE MEDIA GROUP ####
###############################

group:
  media_centre:
      name: Media Centre
      entities:
      - media_player.media_centre

###############################
###### NOW-PLAYING GROUP ######
###############################

  now_playing:
      name: Now Playing
      control: hidden
      entities:
      - input_boolean.plex_movie
      - input_boolean.plex_tvshow

###############################
###### MEDIA - PAGE 2 - #######
###############################

  Page_2:
    name: Page 2
    view: true
    entities:
      - media_player.bravia4k
      - media_player.plex_shield
      - media_player.cast_shield
      - media_player.kodi_kodi
      #
      - media_player.sonos_living_room
      - media_player.sonos_kitchen
      - media_player.sonos_bedroom
      - media_player.sonos_all_universal
      #
      - media_player.media_centre
