###############################
###### UPTIME SENSOR ##########
###############################

sensor:
  - platform: uptime

###############################
###### PIHOLE SENSOR ##########
###############################

  - platform: pi_hole
    host: !secret pihole_ip

###############################
#### SPEEDTEST SENSOR #########
###############################

  - platform: speedtest
    hour:
      - 6
    monitored_conditions:
      - ping
      - download
      - upload

###############################
##### SPEEDTEST GROUP #########
###############################

group:
  speedtest:
    name: Speedtest
    entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
