sensor:
  - platform: template
    sensors:
      james_ping:
        value_template:
          "{% if is_state('device_tracker.james_ping', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      james_tado:
        value_template:
          "{% if is_state('device_tracker.james_tado', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      james_oneplus3:
        value_template:
          "{% if is_state('device_tracker.james_oneplus3', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      gillian_ping:
        value_template:
          "{% if is_state('device_tracker.gillian_ping', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      gillian_tado:
        value_template:
          "{% if is_state('device_tracker.gillian_tado', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      gillian_oneplus3:
        value_template:
          "{% if is_state('device_tracker.gillian_oneplus3', 'home') %}
          is at home
          {% else %}
          is away
          {% endif %}"

  - platform: template
    sensors:
      guest_mode:
        value_template:
          "{% if is_state('input_boolean.enable_guest', 'off') %}
          Enable Guest Mode
          {% else %}
          Disable Guest Mode
          {% endif %}"
