###############################
######### HUE SCRIPTS #########
###############################

  hue_dim:
    alias: Dim
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_full:
    alias: Full
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Full"

  hue_morning:
    alias: Morning
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dim"

  hue_movie:
    alias: Movie
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Movie"

  hue_night:
    alias: Night
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Night"

  hue_white:
    alias: White
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "White"

  hue_outside_full:
    alias: Outside Full
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Outside"
          scene_name: "Full"

  hue_outside_dim:
    alias: Outside Dim
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Outside"
          scene_name: "Dim"
